import "dotenv/config";

export const {
  port,
  jwtSecret,
  dbUser,
  dbPassword,
  dbHost,
  dbName,
  environment,
  isProductionEnvironment,
  oauthClientID,
  oauthClientSecret,
  callback_url,
  facebook_app_id,
  facebook_app_secret,
  github_client_id,
  github_client_secret,
  twitter_consumer_id,
  twitter_consumer_secret
} = {
  isProductionEnvironment: process.env.NODE_ENV === "production",
  port: process.env.PORT || 3000,
  jwtSecret: process.env.PRIVATE_JWT,
  dbUser: process.env.DB_USERNAME,
  dbPassword: process.env.DB_PASSWORD,
  dbHost: process.env.DB_HOST,
  dbName: process.env.DB_NAME,
  environment: process.env.NODE_ENV,
  oauthClientID: process.env.OAUTH_CLIENT_ID,
  oauthClientSecret: process.env.OAUTH_CLIENT_SECRET,
  callback_url:process.env.NODE_ENV === "production"?process.env.CALLBACK_URL:process.env.CALLBACK_URL_DEVELOPMENT+":"+process.env.PORT,
  facebook_app_id:process.env.FACEBOOK_APP_ID,
  facebook_app_secret:process.env.FACEBOOK_APP_SECRET,
  github_client_id:process.env.GITHUB_CLIENT_ID,
  github_client_secret:process.env.GITHUB_CLIENT_SECRET,
  twitter_consumer_id:process.env.TWITTER_CONSUMER_ID,
  twitter_consumer_secret:process.env.TWITTER_CONSUMER_SECRET,
};
